branches:
  only:
    - main

environment:
  matrix:
    # Latest / currently recommended Miniconda
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Miniconda38-x64"

    # Latest Python, if different
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"

    # Oldest Python3 version supported
    - PYTHON: "C:\\Python35-x64"

    # Final Python2 version supported
    - PYTHON: "C:\\Python27-x64"

install:
  - "%PYTHON%\\python.exe -c \"import sys; print(sys.version)\""
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python.exe -m myokit system"
  - "%PYTHON%\\python.exe -m myokit test unit"

