#
# Configuration for travis-ci testing
# This tests ubuntu by default, but can also be made to test on osx
#
sudo: false

# Test on Ubuntu 14
dist: trusty

language: python

matrix:
    include:
        - python: "2.7"
          env:
            - MYOKIT_COVER=false
            - MYOKIT_TEST=true
        - python: "2.7"
          env:
            - MYOKIT_COVER=true
            - MYOKIT_TEST=false


# Install C dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsundials-serial-dev

# Install Python dependencies
install:
  - pip install -e .
  - pip install numpy scipy sympy matplotlib flake8
  - pip install coverage
  - pip install codecov

# Show Python version
before_script:
- python --version

# Run tests
script:
  - if [[ $MYOKIT_COVER == true ]]; then coverage run test --nosub; fi;
  - if [[ $MYOKIT_TEST == true ]]; then python -m flake8; fi;
  - if [[ $MYOKIT_TEST == true ]]; then python test --unit; fi;

# Compile coverage report
after_success:
  - if [[ $MYOKIT_COVER == true ]]; then codecov; fi;

# Send notifications
notifications:
  email:
    recipients:
    - michael.clerx@cs.ox.ac.uk
