#
# Configuration for travis-ci continuous integration
#
sudo: required

# Test on Ubuntu 16
os: linux
dist: xenial

language: python

# Only build main and PRs
branches:
  only:
    - main

# Python version choices:
#
# 2.7.0 --> Released 2010-07-03, no longer testable.
# 2.7.6 --> Released 2013-11-10, no longer testable.
# 2.7   --> Latest 2.7 version. At the moment 2.7.14 on travis (2018-10-31)
# 3.0-3.3 --> Bad initial versions of Python 3; Not supported
# 3.4     --> No longer supported by pip (2019-03)
# 3.5-3.9 --> Tested

matrix:
    # Always put true env variable first, for nicer overview on travis website
    include:
        # Unit tests on Ubuntu
        - python: "2.7"
          env:
            - PYTHON=python
            - MYOKIT_UNIT=true
        - python: "3.5"
          env:
            - PYTHON=python3
            - MYOKIT_UNIT=true
        - python: "3.6"
          env:
            - PYTHON=python3
            - MYOKIT_UNIT=true
        - python: "3.7"
          env:
            - PYTHON=python3
            - MYOKIT_UNIT=true
        - python: "3.8"
          env:
            - PYTHON=python3
            - MYOKIT_UNIT=true
        # Cover checking + latest version
        - python: "3.9"
          env:
            - PYTHON=python3
            - MYOKIT_COVER=true
        # Style checking
        - python: "3.9"
          env:
            - PYTHON=python3
            - MYOKIT_STYLE=true
        # Doctests
        - python: "3.9"
          env:
            - PYTHON=python3
            - MYOKIT_DOC=true
        # Test without optional dependencies
        - python: "3.9"
          env:
            - MYOKIT_BASIC=true
            - MYOKIT_UNIT=true
        # Unit tests on OS/X
        - os: osx
          osx_image: xcode11.2
          language: shell
          env:
            - PYTHON=python3
            - MYOKIT_UNIT=true

# Install CVODE dependencies
before_install:
  # Ubuntu
  # Python packages can be installed here but won't work (tests run in virtualenv)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ ! $MYOKIT_STYLE ]]; then
      sudo apt-get -qq update;
      sudo apt-get install -y libsundials-serial-dev;
      sudo apt-get install -y opencl-headers ocl-icd-opencl-dev;
      sudo bash .travis-opencl.sh;
    fi;
  # OS/X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew install sundials;
    fi;

# Install Myokit and extra testing dependencies
install:
  - $PYTHON -m pip install --upgrade pip;
  - if [[ $MYOKIT_BASIC == true ]]; then $PYTHON -m pip install .; else $PYTHON -m pip install .[optional]; fi;
  - if [[ $MYOKIT_COVER == true ]]; then $PYTHON -m pip install coverage codecov; fi;
  - if [[ $MYOKIT_STYLE == true ]]; then $PYTHON -m pip install .[dev]; fi;
  - if [[ $MYOKIT_DOC == true ]]; then $PYTHON -m pip install .[docs,gui]; fi;

# Show system information
before_script:
- $PYTHON -m myokit system

# Run tests
script:
  - if [[ $MYOKIT_UNIT == true ]]; then $PYTHON -m myokit test unit; fi;
  - if [[ $MYOKIT_COVER == true ]]; then coverage3 run -m myokit test unit; fi;
  - if [[ $MYOKIT_STYLE == true ]]; then
        $PYTHON -m flake8 --version;
        $PYTHON -m flake8;
    fi;
  - if [[ $MYOKIT_DOC == true ]]; then
        $PYTHON -m myokit test doc;
    fi;

# Compile coverage report
after_success:
  - if [[ $MYOKIT_COVER == true ]]; then codecov; fi;

# Send notifications
notifications:
  email:
    recipients:
    - michael.clerx@nottingham.ac.uk
