#
# Configuration for travis-ci testing
# This tests ubuntu by default, but can also be made to test on osx
#
sudo: required

# Test on Ubuntu 14
dist: trusty

language: python

env:
  - MYOKIT_UNIT=true
    MYOKIT_COVER=false
    MYOKIT_STYLE=false
    MYOKIT_DOC=false


matrix:
    # Always put true env variable first, for nicer overview on travis website
    include:
        # Unit tests
        - python: "2.7"
          env:
            - MYOKIT_UNIT=true
        - python: "3.4"
          env:
            - MYOKIT_UNIT=true
        - python: "3.5"
          env:
            - MYOKIT_UNIT=true
        - python: "3.6"
          env:
            - MYOKIT_UNIT=true
        # Cover checking
        - python: "3.6"
          env:
            - MYOKIT_COVER=true
        # Style checking
        - python: "3.6"
          env:
            - MYOKIT_STYLE=true
        # Doctests
        - python: "3.6"
          env:
            - MYOKIT_DOC=true

# Install C dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsundials-serial-dev
  # Note: Python packages loaded here are not pulled into the virtualenv,
  # so won't be importable.

# Install Python dependencies
install:
  # Install Myokit with extra dependencies
  - pip install -e .[dev,optional]
  # Install cover checking libraries
  - if [[ $MYOKIT_COVER == true ]]; then pip install coverage codecov; fi;
  # Install style checking code
  - if [[ $MYOKIT_STYLE == true ]]; then pip install flake8; fi;
  # Install doc building code
  - if [[ $MYOKIT_DOC == true ]]; then pip install sphinx; fi;
  # Install GUI libraries
  - if [[ $MYOKIT_DOC == true ]]; then pip3 install pyqt5; fi;

# Show Python version
before_script:
- python --version

# Run tests
script:
  - if [[ $MYOKIT_UNIT == true ]]; then python test --unit; fi;
  - if [[ $MYOKIT_COVER == true ]]; then coverage run test --nosub; fi;
  - if [[ $MYOKIT_STYLE == true ]]; then python -m flake8; fi;
  - if [[ $MYOKIT_DOC == true ]]; then python test --doctest; fi;

# Compile coverage report
after_success:
  - if [[ $MYOKIT_COVER == true ]]; then codecov; fi;

# Send notifications
notifications:
  email:
    recipients:
    - michael.clerx@cs.ox.ac.uk
