#
# Configuration for travis-ci testing
# This tests ubuntu by default, but can also be made to test on osx
#
sudo: false

# Test on Ubuntu 14
dist: trusty

language: python

matrix:
    # Always put true env variable first, for nicer overview on travis website
    include:
        # Unit test Python 2.7
        - python: "2.7"
          env:
            - MYOKIT_TEST_UNIT=true
            - MYOKIT_TEST_COVER=false
            - MYOKIT_TEST_STYLE=false
            - MYOKIT_TEST_DOC=false
        # Cover
        - python: "2.7"
          env:
            - MYOKIT_TEST_COVER=true
            - MYOKIT_TEST_UNIT=false
            - MYOKIT_TEST_STYLE=false
            - MYOKIT_TEST_DOC=false
      # Style check
        - python: "2.7"
          env:
            - MYOKIT_TEST_STYLE=true
            - MYOKIT_TEST_UNIT=false
            - MYOKIT_TEST_COVER=false
            - MYOKIT_TEST_DOC=false
        # Doc test
        #- python: "2.7"
        #  env:
        #    - MYOKIT_TEST_DOC=true
        #    - MYOKIT_TEST_UNIT=false
        #    - MYOKIT_TEST_COVER=false
        #    - MYOKIT_TEST_STYLE=false

# Install C dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsundials-serial-dev
  # Install GUI libraries
  #- if [[ $MYOKIT_TEST_DOC == true ]]; then sudo apt-get install -y python-qt5; fi;

# Install Python dependencies
install:
  # Install main components
  - pip install -e .
  # Install optional extras (needed for unit tests and docs)
  - pip install sympy
  # Install cover checking libraries
  - if [[ $MYOKIT_TEST_COVER == true ]]; then pip install coverage codecov; fi;
  # Install style checking code
  - if [[ $MYOKIT_TEST_STYLE == true ]]; then pip install flake8; fi;
  # Install doc building code
  #- if [[ $MYOKIT_TEST_DOC == true ]]; then pip install sphinx; fi;
  # Install GUI libraries

# Show Python version
before_script:
- python --version

# Run tests
script:
  - if [[ $MYOKIT_TEST_UNIT == true ]]; then python test --unit; fi;
  - if [[ $MYOKIT_TEST_COVER == true ]]; then coverage run test --nosub; fi;
  - if [[ $MYOKIT_TEST_STYLE == true ]]; then python -m flake8; fi;
  #- if [[ $MYOKIT_TEST_DOC == true ]]; then python test --doctest; fi;

# Compile coverage report
after_success:
  - if [[ $MYOKIT_TEST_COVER == true ]]; then codecov; fi;

# Send notifications
notifications:
  email:
    recipients:
    - michael.clerx@cs.ox.ac.uk
