name: Windows unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test-2:
    name: unit-py2
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
          architecture: x64

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install .[optional]

      - name: Run unit tests
        run: |
          python -m myokit system
          python -m myokit test unit

  build-and-test-3:
    name: unit-py3
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install .[optional]

      - name: Run unit tests
        run: |
          python -m myokit system
          python -m myokit test unit
