name: Ubuntu unit tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: unit-ubuntu
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - name: Add intel repo
        run: |
          sudo .github/workflows/install-ubuntu-dependencies.sh

      - name: Install Intel oneapi libs
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: intel-oneapi-runtime-libs
          version: 1

